import "./KnowMore.css";
import { useParams } from "react-router-dom";
import { useEffect, useState } from "react";
import axios from "axios";
import LoadingSpinner from "../../components/LoadingSpinner/LoadingSpinner";

const KnowMore = () => {
  const { result } = useParams();
  const [report, setReport] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const generateReport = async () => {
      setLoading(true);
      setError("");
      try {
        const response = await axios.post(
          "https://openrouter.ai/api/v1/chat/completions",
          {
            model: "mistralai/devstral-2512:free",
            messages: [
              {
                role: "user",
                content: [
                  {
                    type: "text",
                    text: `Generate a highly detailed medical report for a patient with a '${result}' Chest X-Ray result. 
                    
                    Return ONLY raw HTML code (no markdown backticks, no JSON). Use Bootstrap 5 classes for styling.
                    
                    Structure:
                    <div class="card shadow-sm mb-4">
                      <div class="card-header bg-primary text-white">
                        <h2 class="h4 mb-0">Diagnosis: ${result}</h2>
                      </div>
                      <div class="card-body">
                         <h4 class="text-primary mt-3">Understanding the Condition</h4>
                         <p>...</p>
                         
                         <h4 class="text-primary mt-3">Common Symptoms</h4>
                         <ul class="list-group list-group-flush mb-3">...</ul>
                         
                         <div class="alert alert-warning mt-4">
                           <h5 class="alert-heading">Immediate Precautions</h5>
                           <p>...</p>
                         </div>
                         
                         <div class="alert alert-danger mt-3">
                           <h5 class="alert-heading">When to See a Doctor</h5>
                           <p>...</p>
                         </div>
                      </div>
                    </div>
                    
                    Keep the tone professional and reassuring.`
                  }
                ]
              }
            ]
          },
          {
            headers: {
              "Authorization": "Bearer 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",
              "Content-Type": "application/json",
              "HTTP-Referer": "http://localhost:3000",
              "X-Title": "Alveoli"
            }
          }
        );

        if (response.data && response.data.choices && response.data.choices.length > 0) {
          let content = response.data.choices[0].message.content;
          // Strip markdown backticks if present
          content = content.replace(/```html/g, '').replace(/```/g, '');
          setReport(content);
        } else {
          setError("Failed to generate report from AI.");
        }
      } catch (err) {
        console.error(err);
        setError("An error occurred while communicating with the AI service.");
      } finally {
        setLoading(false);
      }
    };

    if (result) {
      generateReport();
    }
  }, [result]);

  return (
    <div className="knowMore__container container d-flex flex-column align-items-center">
      <div className="knowMore__sectionHeading mb-4">
        <p>AI Medical Analysis</p>
      </div>

      {loading && (
        <div className="d-flex flex-column align-items-center mt-5">
          <LoadingSpinner />
          <p className="mt-3 text-muted">Consulting AI Specialist...</p>
        </div>
      )}

      {error && (
        <div className="alert alert-danger mt-5" role="alert">
          {error}
        </div>
      )}

      {!loading && !error && report && (
        <div className="knowMore__containerDiv w-100">
          <div dangerouslySetInnerHTML={{ __html: report }} />
          <div className="mt-4 pt-3 text-muted small text-center">
            <em>Disclaimer: This report is generated by AI. It is for informational purposes only.</em>
          </div>
        </div>
      )}
    </div>
  );
};

export default KnowMore;
